In [1]:
import pandas as pd
import json
import os
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Path to train folder
train_folder = r"C:\Users\HP\Downloads\2021.naacl-main.472.OptionalSupplementaryData\QMSum\ALL\train"

all_data = []

# Loop through all JSON files in the folder
for filename in os.listdir(train_folder):
    if filename.endswith(".json"):
        file_path = os.path.join(train_folder, filename)
        with open(file_path, "r", encoding="utf-8") as f:
            data = json.load(f)
            all_data.append(data)

# Flatten the list if needed (depends on JSON structure)

flat_data = []
for item in all_data:
    if isinstance(item, list):
        flat_data.extend(item)
    else:
        flat_data.append(item)

# Convert to DataFrame
train_df = pd.DataFrame(flat_data)
train_df.head()

,topic_list,general_query_list,specific_query_list,meeting_transcripts
0,[{'topic': 'Current XML format to link up diff...,"[{'query': 'Summarize the whole meeting', 'ans...",[{'query': 'Summarize the discussion about the...,"[{'speaker': 'Grad C', 'content': 'Yeah , we h..."
1,[{'topic': 'Details about setting up the wizar...,"[{'query': 'Summarize the meeting', 'answer': ...",[{'query': 'Summarize the details about settin...,"[{'speaker': 'Grad A', 'content': 'Hey , you '..."
2,"[{'topic': 'Data collection', 'relevant_text_s...","[{'query': 'Summarize the meeting.', 'answer':...",[{'query': 'What was the advantage of using No...,"[{'speaker': 'Grad A', 'content': 'Yeah , I th..."
3,[{'topic': 'Introducing Fey and discussing par...,"[{'query': 'Summarize the meeting', 'answer': ...",[{'query': 'Summarize the discussion about cap...,"[{'speaker': 'Grad G', 'content': 'Time .'}, {..."
4,"[{'topic': 'SmartKom architecture', 'relevant_...",[{'query': 'What was discussed in the meeting?...,[{'query': 'Summarize what was said on SmartKo...,"[{'speaker': 'Grad C', 'content': 'Hmm . Testi..."

### Converting the Json files to a readeable dataset format

In [2]:
import os
import json
import pandas as pd

INPUT_FOLDER = r"C:\Users\HP\Downloads\2021.naacl-main.472.OptionalSupplementaryData\QMSum\ALL\train"
OUTPUT_CSV = "dataset.csv"
OUTPUT_XLSX = "dataset.xlsx"

rows = []

def build_conversation(transcripts):
    convo = ""
    for turn in transcripts:
        speaker = turn.get("speaker", "")
        text = turn.get("content", "")
        convo += f"{speaker}: {text}\n"
    return convo

for filename in os.listdir(INPUT_FOLDER):
    if not filename.endswith(".json"):
        continue

    filepath = os.path.join(INPUT_FOLDER, filename)

    with open(filepath, "r", encoding="utf-8") as f:
        data = json.load(f)

    conversation = build_conversation(data["meeting_transcripts"])

    # ----- General queries -----
    for q in data.get("general_query_list", []):
        rows.append({
            "Conversation": conversation.strip(),
            "Query": q["query"],
            "Answer": q["answer"],
            "Source_File": filename
        })

    # ----- Specific queries -----
    for q in data.get("specific_query_list", []):
        span = q.get("relevant_text_span", [])

        if span:
            start = int(span[0][0])
            end = int(span[0][1])
            snippet = conversation[start:end]
        else:
            snippet = conversation

        rows.append({
            "Conversation": snippet.strip(),
            "Query": q["query"],
            "Answer": q["answer"],
            "Source_File": filename
        })

# Create dataframe
df = pd.DataFrame(rows)

# Save outputs
df.to_csv(OUTPUT_CSV, index=False)
df.to_excel(OUTPUT_XLSX, index=False)

print("Dataset successfully created!")
print(f"Rows: {len(df)}")
print(f"Files saved: {OUTPUT_CSV}, {OUTPUT_XLSX}")

Dataset successfully created!
Rows: 1257
Files saved: dataset.csv, dataset.xlsx

In [3]:
df.head(2)

,Conversation,Query,Answer,Source_File
0,"Grad C: Yeah , we had a long discussion about ...",Summarize the whole meeting,Meeting participants wanted to agree upon a st...,Bdb001.json
1,ad a long discussion about how much w how easy...,Summarize the discussion about the current XML...,C developed an XML format that links together ...,Bdb001.json

In [4]:
df['Conversation'].head(1)

0    Grad C: Yeah , we had a long discussion about ...
Name: Conversation, dtype: object

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1257 entries, 0 to 1256
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Conversation  1257 non-null   object
 1   Query         1257 non-null   object
 2   Answer        1257 non-null   object
 3   Source_File   1257 non-null   object
dtypes: object(4)
memory usage: 39.4+ KB

In [6]:
df = df.drop('Source_File', axis = 1)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1257 entries, 0 to 1256
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Conversation  1257 non-null   object
 1   Query         1257 non-null   object
 2   Answer        1257 non-null   object
dtypes: object(3)
memory usage: 29.6+ KB

In [8]:
# Save outputs
df.to_csv(OUTPUT_CSV, index=False)
df.to_excel(OUTPUT_XLSX, index=False)

print("Dataset successfully created!")
print(f"Rows: {len(df)}")
print(f"Files saved: {OUTPUT_CSV}, {OUTPUT_XLSX}")

Dataset successfully created!
Rows: 1257
Files saved: dataset.csv, dataset.xlsx

In [9]:
import os
os.getcwd()

'C:\\Users\\HP\\Downloads\\2021.naacl-main.472.OptionalSupplementaryData'